import { BuyerRequest, Evidence } from './types';

export const mockEvidence: Evidence[] = [
   {
      id: '1',
      name: 'ISO 9001:2015 Certification',
      docType: 'Certificate',
      status: 'active',
      expiryDate: new Date('2026-12-31'),
      versions: [
         {
            id: 'v1-1',
            versionNumber: 1,
            uploadedAt: new Date('2024-01-15'),
            uploadedBy: 'John Doe',
            notes: 'Initial certification',
            fileSize: 2048,
         },
         {
            id: 'v1-2',
            versionNumber: 2,
            uploadedAt: new Date('2024-06-20'),
            uploadedBy: 'Jane Smith',
            notes: 'Updated with new scope',
            fileSize: 2156,
         },
      ],
      owner: 'Quality Team',
      createdDate: new Date('2024-01-15'),
      description: 'Quality Management System Certification',
      lastUpdated: new Date('2024-06-20'),
   },
   {
      id: '2',
      name: 'Business License',
      docType: 'License',
      status: 'expiring',
      expiryDate: new Date('2026-03-15'),
      versions: [
         {
            id: 'v2-1',
            versionNumber: 1,
            uploadedAt: new Date('2023-03-15'),
            uploadedBy: 'Admin',
            notes: 'Original license',
            fileSize: 1024,
         },
      ],
      owner: 'Legal Department',
      createdDate: new Date('2023-03-15'),
      description: 'State Business Operating License',
      lastUpdated: new Date('2023-03-15'),
   },
   {
      id: '3',
      name: 'Annual Audit Report 2024',
      docType: 'Audit',
      status: 'active',
      expiryDate: new Date('2027-12-31'),
      versions: [
         {
            id: 'v3-1',
            versionNumber: 1,
            uploadedAt: new Date('2024-03-10'),
            uploadedBy: 'Audit Team',
            notes: 'FY2024 Audit',
            fileSize: 5120,
         },
      ],
      owner: 'Finance',
      createdDate: new Date('2024-03-10'),
      description: 'Annual Financial Audit Report',
      lastUpdated: new Date('2024-03-10'),
   },
   {
      id: '4',
      name: 'Environmental Compliance Report',
      docType: 'Report',
      status: 'active',
      expiryDate: new Date('2026-06-30'),
      versions: [
         {
            id: 'v4-1',
            versionNumber: 1,
            uploadedAt: new Date('2024-02-01'),
            uploadedBy: 'Compliance Officer',
            notes: 'Q1 2024 Report',
            fileSize: 3072,
         },
         {
            id: 'v4-2',
            versionNumber: 2,
            uploadedAt: new Date('2024-05-15'),
            uploadedBy: 'Compliance Officer',
            notes: 'Q2 2024 Report',
            fileSize: 3200,
         },
      ],
      owner: 'Compliance',
      createdDate: new Date('2024-02-01'),
      description: 'Environmental Impact and Compliance Assessment',
      lastUpdated: new Date('2024-05-15'),
   },
   {
      id: '5',
      name: 'SOC 2 Type II Report',
      docType: 'Report',
      status: 'active',
      expiryDate: new Date('2025-12-31'),
      versions: [
         {
            id: 'v5-1',
            versionNumber: 1,
            uploadedAt: new Date('2023-12-01'),
            uploadedBy: 'Security Team',
            notes: 'SOC 2 Type II Audit',
            fileSize: 4096,
         },
      ],
      owner: 'Security',
      createdDate: new Date('2023-12-01'),
      description: 'System and Organization Controls Report',
      lastUpdated: new Date('2023-12-01'),
   },
   {
      id: '6',
      name: 'Food Safety Certification',
      docType: 'Certificate',
      status: 'expired',
      expiryDate: new Date('2024-08-15'),
      versions: [
         {
            id: 'v6-1',
            versionNumber: 1,
            uploadedAt: new Date('2022-08-15'),
            uploadedBy: 'Operations',
            notes: 'FSSC 22000 Certification',
            fileSize: 1536,
         },
      ],
      owner: 'Operations',
      createdDate: new Date('2022-08-15'),
      description: 'Food Safety System Certification',
      lastUpdated: new Date('2022-08-15'),
   },
   {
      id: '7',
      name: 'Insurance Certificate',
      docType: 'Certificate',
      status: 'active',
      expiryDate: new Date('2026-09-30'),
      versions: [
         {
            id: 'v7-1',
            versionNumber: 1,
            uploadedAt: new Date('2024-09-30'),
            uploadedBy: 'Finance',
            notes: 'General Liability Insurance',
            fileSize: 512,
         },
      ],
      owner: 'Finance',
      createdDate: new Date('2024-09-30'),
      description: 'General Liability and Property Insurance',
      lastUpdated: new Date('2024-09-30'),
   },
   {
      id: '8',
      name: 'Data Privacy Policy',
      docType: 'Report',
      status: 'active',
      expiryDate: new Date('2027-01-31'),
      versions: [
         {
            id: 'v8-1',
            versionNumber: 1,
            uploadedAt: new Date('2024-01-31'),
            uploadedBy: 'Legal',
            notes: 'GDPR Compliant Policy',
            fileSize: 768,
         },
         {
            id: 'v8-2',
            versionNumber: 2,
            uploadedAt: new Date('2024-07-15'),
            uploadedBy: 'Legal',
            notes: 'Updated for CCPA',
            fileSize: 856,
         },
      ],
      owner: 'Legal',
      createdDate: new Date('2024-01-31'),
      description: 'Data Privacy and Protection Policy',
      lastUpdated: new Date('2024-07-15'),
   },
   {
      id: '9',
      name: 'Training Completion Records',
      docType: 'Report',
      status: 'active',
      expiryDate: new Date('2026-12-31'),
      versions: [
         {
            id: 'v9-1',
            versionNumber: 1,
            uploadedAt: new Date('2024-04-01'),
            uploadedBy: 'HR',
            notes: 'Safety Training Records',
            fileSize: 2048,
         },
      ],
      owner: 'HR',
      createdDate: new Date('2024-04-01'),
      description: 'Employee Safety and Compliance Training Records',
      lastUpdated: new Date('2024-04-01'),
   },
   {
      id: '10',
      name: 'Quality Control Procedures',
      docType: 'Report',
      status: 'active',
      expiryDate: new Date('2027-06-30'),
      versions: [
         {
            id: 'v10-1',
            versionNumber: 1,
            uploadedAt: new Date('2024-06-30'),
            uploadedBy: 'Quality Team',
            notes: 'Updated QC Procedures',
            fileSize: 1280,
         },
      ],
      owner: 'Quality Team',
      createdDate: new Date('2024-06-30'),
      description: 'Quality Control and Testing Procedures',
      lastUpdated: new Date('2024-06-30'),
   },
];

export const mockBuyerRequests: BuyerRequest[] = [
   {
      id: 'req-1',
      docType: 'Certificate',
      dueDate: new Date('2026-02-15'),
      status: 'pending',
      buyerName: 'Acme Corp',
      requestedAt: new Date('2026-01-10'),
   },
   {
      id: 'req-2',
      docType: 'Audit',
      dueDate: new Date('2026-01-20'),
      status: 'pending',
      buyerName: 'Global Supplies Inc',
      requestedAt: new Date('2026-01-05'),
   },
   {
      id: 'req-3',
      docType: 'Report',
      dueDate: new Date('2025-12-31'),
      status: 'overdue',
      buyerName: 'Tech Partners Ltd',
      requestedAt: new Date('2025-12-01'),
   },
   {
      id: 'req-4',
      docType: 'License',
      dueDate: new Date('2026-03-01'),
      status: 'fulfilled',
      buyerName: 'Premium Distributors',
      requestedAt: new Date('2026-01-08'),
   },
];
